/*
    File:    aux_expr_scaner_classes_table.cpp
    Created: 03 April 2018 at 18:57 Moscow time
    Author:  Гаврилов Владимир Сергеевич
    E-mails: vladimir.s.gavrilov@gmail.com
             gavrilov.vladimir.s@mail.ru
             gavvs1977@yandex.ru
*/

#include "../include/aux_expr_scaner_classes_table.h"

const Elem<Aux_expr_lexem_code> a_classes_jump_table[] = {
    {const_cast<char32_t*>(U"ae"),Aux_expr_lexem_code::M_Class_Latin,  1},  // 0:   [:L...
    {const_cast<char32_t*>(U"t"), Aux_expr_lexem_code::M_Class_Latin,  3},  // 1:   [:La...
    {const_cast<char32_t*>(U"t"), Aux_expr_lexem_code::M_Class_Letter, 4},  // 2:   [:Le...
    {const_cast<char32_t*>(U"i"), Aux_expr_lexem_code::M_Class_Latin,  5},  // 3:   [:Lat...
    {const_cast<char32_t*>(U"t"), Aux_expr_lexem_code::M_Class_Letter, 6},  // 4:   [:Let...
    {const_cast<char32_t*>(U"n"), Aux_expr_lexem_code::M_Class_Latin,  7},  // 5:   [:Lati...
    {const_cast<char32_t*>(U"e"), Aux_expr_lexem_code::M_Class_Letter, 8},  // 6:   [:Lett...
    {const_cast<char32_t*>(U":"), Aux_expr_lexem_code::M_Class_Latin,  9},  // 7:   [:Latin...
    {const_cast<char32_t*>(U"r"), Aux_expr_lexem_code::M_Class_Letter, 10}, // 8:   [:Lette...
    {const_cast<char32_t*>(U"]"), Aux_expr_lexem_code::M_Class_Latin,  11}, // 9:   [:Latin:...
    {const_cast<char32_t*>(U":"), Aux_expr_lexem_code::M_Class_Letter, 12}, // 10:  [:Letter...
    {const_cast<char32_t*>(U""),  Aux_expr_lexem_code::Class_Latin,    0},  // 11:  [:Latin:]
    {const_cast<char32_t*>(U"]"), Aux_expr_lexem_code::M_Class_Letter, 13}, // 12:  [:Letter:...
    {const_cast<char32_t*>(U""),  Aux_expr_lexem_code::Class_Letter,   0},  // 13:  [:Letter:]

    {const_cast<char32_t*>(U"u"), Aux_expr_lexem_code::M_Class_Russian,15}, // 14:  [:R...
    {const_cast<char32_t*>(U"s"), Aux_expr_lexem_code::M_Class_Russian,16}, // 15:  [:Ru...
    {const_cast<char32_t*>(U"s"), Aux_expr_lexem_code::M_Class_Russian,17}, // 16:  [:Rus...
    {const_cast<char32_t*>(U"i"), Aux_expr_lexem_code::M_Class_Russian,18}, // 17:  [:Russ...
    {const_cast<char32_t*>(U"a"), Aux_expr_lexem_code::M_Class_Russian,19}, // 18:  [:Russi...
    {const_cast<char32_t*>(U"n"), Aux_expr_lexem_code::M_Class_Russian,20}, // 19:  [:Russia...
    {const_cast<char32_t*>(U":"), Aux_expr_lexem_code::M_Class_Russian,21}, // 20:  [:Russian...
    {const_cast<char32_t*>(U"]"), Aux_expr_lexem_code::M_Class_Russian,22}, // 21:  [:Russian:...
    {const_cast<char32_t*>(U""),  Aux_expr_lexem_code::Class_Russian,  0},  // 22:  [:Russian:]

    {const_cast<char32_t*>(U"d"), Aux_expr_lexem_code::M_Class_bdigits,24}, // 23:  [:b...
    {const_cast<char32_t*>(U"i"), Aux_expr_lexem_code::M_Class_bdigits,25}, // 24:  [:bd...
    {const_cast<char32_t*>(U"g"), Aux_expr_lexem_code::M_Class_bdigits,26}, // 25:  [:bdi...
    {const_cast<char32_t*>(U"i"), Aux_expr_lexem_code::M_Class_bdigits,27}, // 26:  [:bdig...
    {const_cast<char32_t*>(U"t"), Aux_expr_lexem_code::M_Class_bdigits,28}, // 27:  [:bdigi...
    {const_cast<char32_t*>(U"s"), Aux_expr_lexem_code::M_Class_bdigits,29}, // 28:  [:bdigit...
    {const_cast<char32_t*>(U":"), Aux_expr_lexem_code::M_Class_bdigits,30}, // 29:  [:bdigits...
    {const_cast<char32_t*>(U"]"), Aux_expr_lexem_code::M_Class_bdigits,31}, // 30:  [:bdigits:...
    {const_cast<char32_t*>(U""),  Aux_expr_lexem_code::Class_bdigits,  0},  // 31:  [:bdigits:]

    {const_cast<char32_t*>(U"i"), Aux_expr_lexem_code::M_Class_digits, 33}, // 32:  [:d...
    {const_cast<char32_t*>(U"g"), Aux_expr_lexem_code::M_Class_digits, 34}, // 33:  [:di...
    {const_cast<char32_t*>(U"i"), Aux_expr_lexem_code::M_Class_digits, 35}, // 34:  [:dig...
    {const_cast<char32_t*>(U"t"), Aux_expr_lexem_code::M_Class_digits, 36}, // 35:  [:digi...
    {const_cast<char32_t*>(U"s"), Aux_expr_lexem_code::M_Class_digits, 37}, // 36:  [:digit...
    {const_cast<char32_t*>(U":"), Aux_expr_lexem_code::M_Class_digits, 38}, // 37:  [:digits...
    {const_cast<char32_t*>(U"]"), Aux_expr_lexem_code::M_Class_digits, 39}, // 38:  [:digits:...
    {const_cast<char32_t*>(U""),  Aux_expr_lexem_code::Class_digits,   0},  // 39:  [:digits:]

    {const_cast<char32_t*>(U"ae"),Aux_expr_lexem_code::M_Class_latin,  41}, // 40:  [:l...
    {const_cast<char32_t*>(U"t"), Aux_expr_lexem_code::M_Class_latin,  43}, // 41:  [:la...
    {const_cast<char32_t*>(U"t"), Aux_expr_lexem_code::M_Class_letter, 44}, // 42:  [:le...
    {const_cast<char32_t*>(U"i"), Aux_expr_lexem_code::M_Class_latin,  45}, // 43:  [:lat...
    {const_cast<char32_t*>(U"t"), Aux_expr_lexem_code::M_Class_letter, 46}, // 44:  [:let...
    {const_cast<char32_t*>(U"n"), Aux_expr_lexem_code::M_Class_latin,  47}, // 45:  [:lati...
    {const_cast<char32_t*>(U"e"), Aux_expr_lexem_code::M_Class_letter, 48}, // 46:  [:lett...
    {const_cast<char32_t*>(U":"), Aux_expr_lexem_code::M_Class_latin,  49}, // 47:  [:latin...
    {const_cast<char32_t*>(U"r"), Aux_expr_lexem_code::M_Class_letter, 50}, // 48:  [:lette...
    {const_cast<char32_t*>(U"]"), Aux_expr_lexem_code::M_Class_latin,  51}, // 49:  [:latin:...
    {const_cast<char32_t*>(U":"), Aux_expr_lexem_code::M_Class_letter, 52}, // 50:  [:letter...
    {const_cast<char32_t*>(U""),  Aux_expr_lexem_code::Class_latin,    0},  // 51:  [:latin:]
    {const_cast<char32_t*>(U"]"), Aux_expr_lexem_code::M_Class_letter, 53}, // 52:  [:letter:...
    {const_cast<char32_t*>(U""),  Aux_expr_lexem_code::Class_letter,   0},  // 53:  [:letter:]

    {const_cast<char32_t*>(U"ds"),Aux_expr_lexem_code::M_Class_ndq,    55}, // 54:  [:n...
    {const_cast<char32_t*>(U"q"), Aux_expr_lexem_code::M_Class_ndq,    57}, // 55:  [:nd...
    {const_cast<char32_t*>(U"q"), Aux_expr_lexem_code::M_Class_nsq,    58}, // 56:  [:ns...
    {const_cast<char32_t*>(U":"), Aux_expr_lexem_code::M_Class_ndq,    59}, // 57:  [:ndq...
    {const_cast<char32_t*>(U":"), Aux_expr_lexem_code::M_Class_nsq,    60}, // 58:  [:nsq...
    {const_cast<char32_t*>(U"]"), Aux_expr_lexem_code::M_Class_ndq,    61}, // 59:  [:ndq:...
    {const_cast<char32_t*>(U"]"), Aux_expr_lexem_code::M_Class_nsq,    62}, // 60:  [:nsq:...
    {const_cast<char32_t*>(U""),  Aux_expr_lexem_code::Class_ndq,      0},  // 61:  [:ndq:]
    {const_cast<char32_t*>(U""),  Aux_expr_lexem_code::Class_nsq,      0},  // 62:  [:nsq:]

    {const_cast<char32_t*>(U"d"), Aux_expr_lexem_code::M_Class_odigits,64}, // 63:  [:o...
    {const_cast<char32_t*>(U"i"), Aux_expr_lexem_code::M_Class_odigits,65}, // 64:  [:od...
    {const_cast<char32_t*>(U"g"), Aux_expr_lexem_code::M_Class_odigits,66}, // 65:  [:odi...
    {const_cast<char32_t*>(U"i"), Aux_expr_lexem_code::M_Class_odigits,67}, // 66:  [:odig...
    {const_cast<char32_t*>(U"t"), Aux_expr_lexem_code::M_Class_odigits,68}, // 67:  [:odigi...
    {const_cast<char32_t*>(U"s"), Aux_expr_lexem_code::M_Class_odigits,69}, // 68:  [:odigit...
    {const_cast<char32_t*>(U":"), Aux_expr_lexem_code::M_Class_odigits,70}, // 69:  [:odigits...
    {const_cast<char32_t*>(U"]"), Aux_expr_lexem_code::M_Class_odigits,71}, // 70:  [:odigits:...
    {const_cast<char32_t*>(U""),  Aux_expr_lexem_code::Class_odigits,  0,}, // 71:  [:odigits:]

    {const_cast<char32_t*>(U"u"), Aux_expr_lexem_code::M_Class_russian,73}, // 72:  [:r...
    {const_cast<char32_t*>(U"s"), Aux_expr_lexem_code::M_Class_russian,74}, // 73:  [:ru...
    {const_cast<char32_t*>(U"s"), Aux_expr_lexem_code::M_Class_russian,75}, // 74:  [:rus...
    {const_cast<char32_t*>(U"i"), Aux_expr_lexem_code::M_Class_russian,76}, // 75:  [:russ...
    {const_cast<char32_t*>(U"a"), Aux_expr_lexem_code::M_Class_russian,77}, // 76:  [:russi...
    {const_cast<char32_t*>(U"n"), Aux_expr_lexem_code::M_Class_russian,78}, // 77:  [:russia...
    {const_cast<char32_t*>(U":"), Aux_expr_lexem_code::M_Class_russian,79}, // 78:  [:russian...
    {const_cast<char32_t*>(U"]"), Aux_expr_lexem_code::M_Class_russian,80}, // 79:  [:russian:...
    {const_cast<char32_t*>(U""),  Aux_expr_lexem_code::Class_russian,  0},  // 80:  [:russian:]

    {const_cast<char32_t*>(U"d"), Aux_expr_lexem_code::M_Class_xdigits,82}, // 81:  [:x...
    {const_cast<char32_t*>(U"i"), Aux_expr_lexem_code::M_Class_xdigits,83}, // 82:  [:xd...
    {const_cast<char32_t*>(U"g"), Aux_expr_lexem_code::M_Class_xdigits,84}, // 83:  [:xdi...
    {const_cast<char32_t*>(U"i"), Aux_expr_lexem_code::M_Class_xdigits,85}, // 84:  [:xdig...
    {const_cast<char32_t*>(U"t"), Aux_expr_lexem_code::M_Class_xdigits,86}, // 85:  [:xdigi...
    {const_cast<char32_t*>(U"s"), Aux_expr_lexem_code::M_Class_xdigits,87}, // 86:  [:xdigit...
    {const_cast<char32_t*>(U":"), Aux_expr_lexem_code::M_Class_xdigits,88}, // 87:  [:xdigits...
    {const_cast<char32_t*>(U"]"), Aux_expr_lexem_code::M_Class_xdigits,89}, // 88:  [:xdigits:...
    {const_cast<char32_t*>(U""),  Aux_expr_lexem_code::Class_xdigits,  0}   // 89:  [:xdigits:]
};