/*
    File:    main_scaner_keyword_table.cpp
    Created: 23 March 2018 at 15:40 Moscow time
    Author:  Гаврилов Владимир Сергеевич
    E-mails: vladimir.s.gavrilov@gmail.com
             gavrilov.vladimir.s@mail.ru
             gavvs1977@yandex.ru
*/

#include "../include/main_scaner_keyword_table.h"

const Elem<Main_lexem_code> a_keyword_jump_table[] = {
    {const_cast<char32_t*>(U"c"),  Main_lexem_code::M_Kw_action,          1},   // 0:   %a...
    {const_cast<char32_t*>(U"t"),  Main_lexem_code::M_Kw_action,          2},   // 1:   %ac...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_action,          3},   // 2:   %act...
    {const_cast<char32_t*>(U"o"),  Main_lexem_code::M_Kw_action,          4},   // 3:   %acti...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_action,          5},   // 4:   %actio...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_action,            0},   // 5:   %action

    {const_cast<char32_t*>(U"lo"), Main_lexem_code::M_Kw_codes,           7},   // 6:   %c...
    {const_cast<char32_t*>(U"a"),  Main_lexem_code::M_Kw_class_members,   9},   // 7:   %cl...
    {const_cast<char32_t*>(U"dm"), Main_lexem_code::M_Kw_codes,           10},  // 8:   %co...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_class_members,   12},  // 9:   %cla...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_codes,           13},  // 10:  %cod...
    {const_cast<char32_t*>(U"m"),  Main_lexem_code::M_Kw_comments,        14},  // 11:  %com...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_class_members,   15},  // 12:  %clas...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_codes,           16},  // 13:  %code...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_comments,        17},  // 14:  %comm...
    {const_cast<char32_t*>(U"_"),  Main_lexem_code::M_Kw_class_members,   18},  // 15:  %class...
    {const_cast<char32_t*>(U"_"),  Main_lexem_code::Kw_codes,             19},  // 16:  %codes...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_comments,        20},  // 17:  %comme...
    {const_cast<char32_t*>(U"m"),  Main_lexem_code::M_Kw_class_members,   21},  // 18:  %class_...
    {const_cast<char32_t*>(U"t"),  Main_lexem_code::M_Kw_codes_type,      22},  // 19:  %codes_...
    {const_cast<char32_t*>(U"t"),  Main_lexem_code::M_Kw_comments,        23},  // 20:  %commen...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_class_members,   24},  // 21:  %class_m...
    {const_cast<char32_t*>(U"y"),  Main_lexem_code::M_Kw_codes_type,      25},  // 22:  %codes_t...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_comments,        26},  // 23:  %comment...
    {const_cast<char32_t*>(U"m"),  Main_lexem_code::M_Kw_class_members,   27},  // 24:  %class_me...
    {const_cast<char32_t*>(U"p"),  Main_lexem_code::M_Kw_codes_type,      28},  // 25:  %codes_ty...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_comments,          0},   // 26:  %comments
    {const_cast<char32_t*>(U"b"),  Main_lexem_code::M_Kw_class_members,   29},  // 27:  %class_mem...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_codes_type,      30},  // 28:  %codes_typ...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_class_members,   31},  // 29:  %class_memb...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_codes_type,        0},   // 30:  %codes_type
    {const_cast<char32_t*>(U"r"),  Main_lexem_code::M_Kw_class_members,   32},  // 31:  %class_membe...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_class_members,   33},  // 32:  %class_member...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_class_members,     0},   // 33:  %class_members

    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_delimiters,      35},  // 34:  %d...
    {const_cast<char32_t*>(U"l"),  Main_lexem_code::M_Kw_delimiters,      36},  // 35:  %de...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_delimiters,      37},  // 36:  %del...
    {const_cast<char32_t*>(U"m"),  Main_lexem_code::M_Kw_delimiters,      38},  // 37:  %deli...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_delimiters,      39},  // 38:  %delim...
    {const_cast<char32_t*>(U"t"),  Main_lexem_code::M_Kw_delimiters,      40},  // 39:  %delimi...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_delimiters,      41},  // 40:  %delimit...
    {const_cast<char32_t*>(U"r"),  Main_lexem_code::M_Kw_delimiters,      42},  // 41:  %delimite...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_delimiters,      43},  // 42:  %delimiter...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_delimiters,        0},   // 43:  %delimiters

    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_header_additions,45},  // 44:  %h...
    {const_cast<char32_t*>(U"a"),  Main_lexem_code::M_Kw_header_additions,46},  // 45:  %he...
    {const_cast<char32_t*>(U"d"),  Main_lexem_code::M_Kw_header_additions,47},  // 46:  %hea...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_header_additions,48},  // 47:  %head...
    {const_cast<char32_t*>(U"r"),  Main_lexem_code::M_Kw_header_additions,49},  // 48:  %heade...
    {const_cast<char32_t*>(U"_"),  Main_lexem_code::M_Kw_header_additions,50},  // 49:  %header...
    {const_cast<char32_t*>(U"a"),  Main_lexem_code::M_Kw_header_additions,51},  // 50:  %header_...
    {const_cast<char32_t*>(U"d"),  Main_lexem_code::M_Kw_header_additions,52},  // 51:  %header_a...
    {const_cast<char32_t*>(U"d"),  Main_lexem_code::M_Kw_header_additions,53},  // 52:  %header_ad...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_header_additions,54},  // 53:  %header_add...
    {const_cast<char32_t*>(U"t"),  Main_lexem_code::M_Kw_header_additions,55},  // 54:  %header_addi...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_header_additions,56},  // 55:  %header_addit...
    {const_cast<char32_t*>(U"o"),  Main_lexem_code::M_Kw_header_additions,57},  // 56:  %header_additi...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_header_additions,58},  // 57:  %header_additio...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_header_additions,59},  // 58:  %header_addition...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_header_additions,  0},   // 59:  %header_additions

    {const_cast<char32_t*>(U"dm"), Main_lexem_code::M_Kw_idents,          61},  // 60:  %i...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_idents,          63},  // 61:  %id...
    {const_cast<char32_t*>(U"p"),  Main_lexem_code::M_Kw_impl_additions,  64},  // 62:  %im...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_idents,          65},  // 63:  %ide...
    {const_cast<char32_t*>(U"l"),  Main_lexem_code::M_Kw_impl_additions,  66},  // 64:  %imp...
    {const_cast<char32_t*>(U"t"),  Main_lexem_code::M_Kw_idents,          67},  // 65:  %iden...
    {const_cast<char32_t*>(U"_"),  Main_lexem_code::M_Kw_impl_additions,  68},  // 66:  %impl...
    {const_cast<char32_t*>(U"_s"), Main_lexem_code::M_Kw_idents,          69},  // 67:  %ident...
    {const_cast<char32_t*>(U"a"),  Main_lexem_code::M_Kw_impl_additions,  71},  // 68:  %impl_...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_ident_name,      72},  // 69:  %ident_...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_idents,            0},   // 70:  %idents
    {const_cast<char32_t*>(U"d"),  Main_lexem_code::M_Kw_impl_additions,  73},  // 71:  %impl_a...
    {const_cast<char32_t*>(U"a"),  Main_lexem_code::M_Kw_ident_name,      74},  // 72:  %ident_n...
    {const_cast<char32_t*>(U"d"),  Main_lexem_code::M_Kw_impl_additions,  75},  // 73:  %impl_ad...
    {const_cast<char32_t*>(U"m"),  Main_lexem_code::M_Kw_ident_name,      76},  // 74:  %ident_na...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_impl_additions,  77},  // 75:  %impl_add...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_ident_name,      78},  // 76:  %ident_nam...
    {const_cast<char32_t*>(U"t"),  Main_lexem_code::M_Kw_impl_additions,  79},  // 77:  %impl_addi...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_ident_name,        0},   // 78:  %ident_name
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_impl_additions,  80},  // 79:  %impl_addit...
    {const_cast<char32_t*>(U"o"),  Main_lexem_code::M_Kw_impl_additions,  81},  // 80:  %impl_additi...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_impl_additions,  82},  // 81:  %impl_additio...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_impl_additions,  83},  // 82:  %impl_addition...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_impl_additions,  0},     // 83:  %impl_additions

    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_keywords,        85},  // 84:  %k...
    {const_cast<char32_t*>(U"y"),  Main_lexem_code::M_Kw_keywords,        86},  // 85:  %ke...
    {const_cast<char32_t*>(U"w"),  Main_lexem_code::M_Kw_keywords,        87},  // 86:  %key...
    {const_cast<char32_t*>(U"o"),  Main_lexem_code::M_Kw_keywords,        88},  // 87:  %keyw...
    {const_cast<char32_t*>(U"r"),  Main_lexem_code::M_Kw_keywords,        89},  // 88:  %keywo...
    {const_cast<char32_t*>(U"d"),  Main_lexem_code::M_Kw_keywords,        90},  // 89:  %keywor...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_keywords,        91},  // 90:  %keyword...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_keywords,          0},   // 91:  %keywords

    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_lexem_info_name, 93},  // 92:  %l...
    {const_cast<char32_t*>(U"x"),  Main_lexem_code::M_Kw_lexem_info_name, 94},  // 93:  %le...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_lexem_info_name, 95},  // 94:  %lex...
    {const_cast<char32_t*>(U"m"),  Main_lexem_code::M_Kw_lexem_info_name, 96},  // 95:  %lexe...
    {const_cast<char32_t*>(U"_"),  Main_lexem_code::M_Kw_lexem_info_name, 97},  // 96:  %lexem...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_lexem_info_name, 98},  // 97:  %lexem_...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_lexem_info_name, 99},  // 98:  %lexem_i...
    {const_cast<char32_t*>(U"f"),  Main_lexem_code::M_Kw_lexem_info_name, 100}, // 99:  %lexem_in...
    {const_cast<char32_t*>(U"o"),  Main_lexem_code::M_Kw_lexem_info_name, 101}, // 100: %lexem_inf...
    {const_cast<char32_t*>(U"_"),  Main_lexem_code::M_Kw_lexem_info_name, 102}, // 101: %lexem_info...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_lexem_info_name, 103}, // 102: %lexem_info_...
    {const_cast<char32_t*>(U"a"),  Main_lexem_code::M_Kw_lexem_info_name, 104}, // 103: %lexem_info_n...
    {const_cast<char32_t*>(U"m"),  Main_lexem_code::M_Kw_lexem_info_name, 105}, // 104: %lexem_info_na...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_lexem_info_name, 106}, // 105: %lexem_info_nam...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_lexem_info_name,   0},   // 106: %lexem_info_name

    {const_cast<char32_t*>(U"u"),  Main_lexem_code::M_Kw_multilined,      108}, // 107: %m...
    {const_cast<char32_t*>(U"l"),  Main_lexem_code::M_Kw_multilined,      109}, // 108: %mu...
    {const_cast<char32_t*>(U"t"),  Main_lexem_code::M_Kw_multilined,      110}, // 109: %mul...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_multilined,      111}, // 110: %mult...
    {const_cast<char32_t*>(U"l"),  Main_lexem_code::M_Kw_multilined,      112}, // 111: %multi...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_multilined,      113}, // 112: %multil...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_multilined,      114}, // 113: %multili...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_multilined,      115}, // 114: %multilin...
    {const_cast<char32_t*>(U"d"),  Main_lexem_code::M_Kw_multilined,      116}, // 115: %multiline...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_multilined,        0},   // 116: %multilined

    {const_cast<char32_t*>(U"eu"), Main_lexem_code::M_Kw_numbers,         118}, // 117: %n...
    {const_cast<char32_t*>(U"sw"), Main_lexem_code::M_Kw_nested,          120}, // 118: %ne...
    {const_cast<char32_t*>(U"m"),  Main_lexem_code::M_Kw_numbers,         122}, // 119: %nu...
    {const_cast<char32_t*>(U"t"),  Main_lexem_code::M_Kw_nested,          123}, // 120: %nes...
    {const_cast<char32_t*>(U"l"),  Main_lexem_code::M_Kw_newline_is_lexem,124}, // 121: %new...
    {const_cast<char32_t*>(U"b"),  Main_lexem_code::M_Kw_numbers,         125}, // 122: %num...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_nested,          126}, // 123: %nest...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_newline_is_lexem,127}, // 124: %newl...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_numbers,         128}, // 125: %numb...
    {const_cast<char32_t*>(U"d"),  Main_lexem_code::M_Kw_nested,          129}, // 126: %neste...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_newline_is_lexem,130}, // 127: %newli...
    {const_cast<char32_t*>(U"r"),  Main_lexem_code::M_Kw_numbers,         131}, // 128: %numbe...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_nested,            0},   // 129: %nested
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_newline_is_lexem,132}, // 130: %newlin...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_numbers,         133}, // 131: %number...
    {const_cast<char32_t*>(U"_"),  Main_lexem_code::M_Kw_newline_is_lexem,134}, // 132: %newline...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_numbers,           0},   // 133: %numbers
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_newline_is_lexem,135}, // 134: %newline_...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_newline_is_lexem,136}, // 135: %newline_i...
    {const_cast<char32_t*>(U"_"),  Main_lexem_code::M_Kw_newline_is_lexem,137}, // 136: %newline_is...
    {const_cast<char32_t*>(U"l"),  Main_lexem_code::M_Kw_newline_is_lexem,138}, // 137: %newline_is_...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_newline_is_lexem,139}, // 138: %newline_is_l...
    {const_cast<char32_t*>(U"x"),  Main_lexem_code::M_Kw_newline_is_lexem,140}, // 139: %newline_is_le...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_newline_is_lexem,141}, // 140: %newline_is_lex...
    {const_cast<char32_t*>(U"m"),  Main_lexem_code::M_Kw_newline_is_lexem,142}, // 141: %newline_is_lexe...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_newline_is_lexem,  0},   // 142: %newline_is_lexem

    {const_cast<char32_t*>(U"cit"),Main_lexem_code::M_Kw_scaner_name,     144}, // 143: %s...
    {const_cast<char32_t*>(U"a"),  Main_lexem_code::M_Kw_scaner_name,     147}, // 144: %sc...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_single_lined,    148}, // 145: %si...
    {const_cast<char32_t*>(U"r"),  Main_lexem_code::M_Kw_strings,         149}, // 146: %st...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_scaner_name,     150}, // 147: %sca...
    {const_cast<char32_t*>(U"g"),  Main_lexem_code::M_Kw_single_lined,    151}, // 148: %sin...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_strings,         152}, // 149: %str...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_scaner_name,     153}, // 150: %scan...
    {const_cast<char32_t*>(U"l"),  Main_lexem_code::M_Kw_single_lined,    154}, // 151: %sing...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_strings,         155}, // 152: %stri...
    {const_cast<char32_t*>(U"r"),  Main_lexem_code::M_Kw_scaner_name,     156}, // 153: %scane...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_single_lined,    157}, // 154: %singl...
    {const_cast<char32_t*>(U"g"),  Main_lexem_code::M_Kw_strings,         158}, // 155: %strin...
    {const_cast<char32_t*>(U"_"),  Main_lexem_code::M_Kw_scaner_name,     159}, // 156: %scaner...
    {const_cast<char32_t*>(U"_"),  Main_lexem_code::M_Kw_single_lined,    160}, // 157: %single...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_strings,         161}, // 158: %string...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_scaner_name,     162}, // 159: %scaner_...
    {const_cast<char32_t*>(U"l"),  Main_lexem_code::M_Kw_single_lined,    163}, // 160: %single_...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_strings,           0},   // 161: %strings
    {const_cast<char32_t*>(U"a"),  Main_lexem_code::M_Kw_scaner_name,     164}, // 162: %scaner_n...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_single_lined,    165}, // 163: %single_l...
    {const_cast<char32_t*>(U"m"),  Main_lexem_code::M_Kw_scaner_name,     166}, // 164: %scaner_na...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_single_lined,    167}, // 165: %single_li...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_scaner_name,     168}, // 166: %scaner_nam...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_single_lined,    169}, // 167: %single_lin...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_scaner_name,       0},   // 168: %scaner_name
    {const_cast<char32_t*>(U"d"),  Main_lexem_code::M_Kw_single_lined,    170}, // 169: %single_line...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_single_lined,      0},   // 170: %single_lined

    {const_cast<char32_t*>(U"o"),  Main_lexem_code::M_Kw_token_fields,    172}, // 171: %t...
    {const_cast<char32_t*>(U"k"),  Main_lexem_code::M_Kw_token_fields,    173}, // 172: %to...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_token_fields,    174}, // 173: %tok...
    {const_cast<char32_t*>(U"n"),  Main_lexem_code::M_Kw_token_fields,    175}, // 174: %toke...
    {const_cast<char32_t*>(U"_"),  Main_lexem_code::M_Kw_token_fields,    176}, // 175: %token...
    {const_cast<char32_t*>(U"f"),  Main_lexem_code::M_Kw_token_fields,    177}, // 176: %token_...
    {const_cast<char32_t*>(U"i"),  Main_lexem_code::M_Kw_token_fields,    178}, // 177: %token_f...
    {const_cast<char32_t*>(U"e"),  Main_lexem_code::M_Kw_token_fields,    179}, // 178: %token_fi...
    {const_cast<char32_t*>(U"l"),  Main_lexem_code::M_Kw_token_fields,    180}, // 179: %token_fie...
    {const_cast<char32_t*>(U"d"),  Main_lexem_code::M_Kw_token_fields,    181}, // 180: %token_fiel...
    {const_cast<char32_t*>(U"s"),  Main_lexem_code::M_Kw_token_fields,    182}, // 181: %token_field...
    {const_cast<char32_t*>(U""),   Main_lexem_code::Kw_token_fields,      0}    // 182: %token_fields
};